### ISSUE TITLE
ffmpeg exits

### ISSUE THREAD

**Issue by Zumbalamambo** [YassineFadhlaoui/Real-Time-Video-Streaming#1]
Im getting the following error,

```
http server on 8080
running on /home/montassar/rtsp
running on 127.0.0.1
ffmpeg exited with code 1
```

**Comment by YassineFadhlaoui** [comment]
maybe because you didn't start **a streaming source**. You should have a video source so that the server can get traffic from the streaming source and diffuse it. you can use *vlc* to stream a video over (rtsp/rtp).
